version: '2'

services:

  redis:
    # mmp123WOCAO
    image: redis:latest
    volumes:
      - ../redis/conf:/etc/redis:ro
      - ../redis/data:/data
    command:
      - redis-server
      - /etc/redis/redis.conf
    ports:
      - 6379:6379

  mysql:
    # easygo
    # root
    # J4KZOW5V*YE27zj2
    image: mysql:5.7
    volumes:
      - ../mysql/conf:/etc/mysql:ro
      - ../mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: xiao19920115
      MYSQL_USER: root
    ports:
      - 3306:3306

  php:
    build: ./php
    volumes:
      - ../php/conf/php.ini:/etc/php.ini:ro
      - ../php/conf/php-fpm.conf:/etc/php-fpm.conf:ro
      - ../project:/project
    links:
      - redis
      - mysql
    ports:
      - 9000:9000
    stdin_open: true
    tty: true

  nginx:
    image: nginx:stable
    volumes:
      - ../nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/conf/conf.d:/etc/nginx/conf.d:ro
      - ../nginx/conf/fastcgi.conf:/etc/nginx/fastcgi.conf:ro
      - ../project:/project
    links:
      - php
    ports:
      - 80:80
      - 443:443
